Repository UPB-PMRust/upb-pmrust.github.io, pull requests merged in 2024-02, with the labels that each got.

#1 Update the github organization name
  .github/labeler.yml
  docusaurus.config.ts
Labels: workflow, website

#3 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: workflow

#2 Add first page and favicon
  docusaurus.config.ts
  src/components/HomepageFeatures/index.tsx
  src/pages/index.tsx
  static/img/device.svg
  static/img/docusaurus-social-card.jpg
  static/img/docusaurus-social-card.png
  static/img/docusaurus.png
  static/img/favicon.ico
  static/img/logo.svg
  static/img/pi-pico-w.svg
  static/img/pm_fils_logo.png
  static/img/rust_logo.svg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
Labels: website

#5 Rename labels
  .github/labeler.yml
Labels: bug, workflow

#11 Rename homework label to project label
  .github/labeler.yml
Labels: workflow

#10 Add cname to the deploy workflow
  .github/workflows/deploy.yml
Labels: workflow

#12 Add welcome page
  docs/lab/_category_.json
  docs/lecture/01.md
  docs/lecture/_category_.json
  docs/project.md
  docs/welcome/images/alexandru_radovici.jpg
  docs/welcome/images/andrei_zamfir.jpg
  docs/welcome/images/danut_aldea.jpg
  docs/welcome/images/irina_bradu.jpg
  docs/welcome/images/irina_nita.jpg
  docs/welcome/images/teodor_dicu.jpg
  docs/welcome/index.md
  src/components/HomepageFeatures/index.tsx
  src/pages/index.tsx
  static/img/device.svg
  static/img/kicad.svg
Labels: website, lab, lecture, project

#14 License
  LICENSE
  docusaurus.config.ts
Labels: website

#13 Lab0 - Tour of rust
  docs/lab/00.md
  docs/lab/01.md
Labels: lab

#28 Fix tip type in lab00
  docs/lab/00.md
Labels: lab

#32 Placeholders for lab01 and lab02
  docs/lab/01.md
  docs/lab/02.md
Labels: lab

#9 Update project.md
  docs/project.md
Labels: project

#36 Kicad setup
  docs/tutorials/_category_.json
  docs/tutorials/images/3d_model_center.png
  docs/tutorials/images/3d_model_offset.png
  docs/tutorials/images/change_footprint.png
  docs/tutorials/images/change_footprint_2.png
  docs/tutorials/images/footprint_editor.png
  docs/tutorials/images/footprint_libraries.png
  docs/tutorials/images/footprint_properties.png
  docs/tutorials/images/new_project.png
  docs/tutorials/images/symbol_editor.png
  docs/tutorials/images/symbol_libraries.png
  docs/tutorials/images/symbol_libraries_import.png
  docs/tutorials/images/symbol_properties.png
  docs/tutorials/kicad.md
  docusaurus.config.ts
Labels: website
